print('Задание по словарям')
my_dict={'Anna':94,'Goga':37,'Felix':51}
print(my_dict,'вес в кг членов группы здоровья')
Existing_value=(my_dict['Goga'])
print('Existing value:', Existing_value)
print(my_dict['Goga'],'вывод значения ключа')
print(my_dict.get('Goga'),' вывод значения ключа')
Not_existing_value=my_dict['Alisa']=123
print('Not_existing_value',Not_existing_value)
print(my_dict, 'обращение к несуществующему ключу и его добавление в словарь')
my_dict.update({'Fima':101,'Pasha':75})
print(my_dict,'с добавлением двух пар')
Deleted_value=my_dict.pop('Felix')
print('Deleted value:',Deleted_value)
print(my_dict,Deleted_value,', без удалённого элемента Felix с выводом его значения')
print('Modified_dictionary:',my_dict)
print('Задание по множеству')
my_set={1, 1, 8, 7, 8, 'pepper', (8,7,15)}
print(my_set)
my_set.add('fox')
my_set.add(12345)
print('Modified set: ',my_set,'добавление в множество двух элементов fox и 12345')
print(my_set.remove('pepper'),' - удаление элемента pepper')
print(my_set)